-- Generated by Oracle SQL Developer Data Modeler 18.1.0.082.1035
--   at:        2018-08-29 19:58:18 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE dim_cliente CASCADE CONSTRAINTS;

DROP TABLE dim_operacao CASCADE CONSTRAINTS;

DROP TABLE dim_produto CASCADE CONSTRAINTS;

DROP TABLE dim_tempo CASCADE CONSTRAINTS;

DROP TABLE dim_vendedor CASCADE CONSTRAINTS;

DROP TABLE fto_venda CASCADE CONSTRAINTS;

CREATE TABLE dim_cliente (
    sk_cliente   NUMBER NOT NULL,
    cd_cliente   NUMBER NOT NULL,
    nm_cliente   VARCHAR2(50) NOT NULL,
    nm_cidade    VARCHAR2(40) NOT NULL,
    sg_uf        VARCHAR2(30) NOT NULL
);

ALTER TABLE dim_cliente ADD CONSTRAINT dim_cliente_pk PRIMARY KEY ( sk_cliente );

CREATE TABLE dim_operacao (
    sk_operador   NUMBER NOT NULL,
    cd_operacao   NUMBER NOT NULL,
    nm_operacao   VARCHAR2(50) NOT NULL
);

ALTER TABLE dim_operacao ADD CONSTRAINT dim_operacao_pk PRIMARY KEY ( sk_operador );

CREATE TABLE dim_produto (
    sk_produto    NUMBER NOT NULL,
    cd_produto    NUMBER NOT NULL,
    nm_produto    VARCHAR2(50) NOT NULL,
    nm_familia    VARCHAR2(40) NOT NULL,
    nm_grupo      VARCHAR2(30) NOT NULL,
    nm_subgrupo   VARCHAR2(30) NOT NULL,
    nm_marca      VARCHAR2(30) NOT NULL,
    nm_linha      VARCHAR2(30)
);

ALTER TABLE dim_produto ADD CONSTRAINT dim_produto_pk PRIMARY KEY ( sk_produto );

CREATE TABLE dim_tempo (
    sk_tempo        NUMBER NOT NULL,
    dt_venda        DATE NOT NULL,
    nr_dia          NUMBER(2) NOT NULL,
    nm_dia_semana   VARCHAR2(15) NOT NULL,
    nr_mes          NUMBER(2) NOT NULL,
    nr_ano          NUMBER(4) NOT NULL
);

ALTER TABLE dim_tempo ADD CONSTRAINT dim_tempo_pk PRIMARY KEY ( sk_tempo );

CREATE TABLE dim_vendedor (
    sk_vendedor   NUMBER NOT NULL,
    cd_vendedor   NUMBER NOT NULL,
    nm_vendedor   VARCHAR2(50) NOT NULL
);

ALTER TABLE dim_vendedor ADD CONSTRAINT dim_vendedor_pk PRIMARY KEY ( sk_vendedor );

CREATE TABLE fto_venda (
    sk_venda         NUMBER NOT NULL,
    qt_venda         NUMBER(8,2) NOT NULL,
    vl_preco_bruto   NUMBER(10,2) NOT NULL,
    vl_preco_ipi     NUMBER(10,2) NOT NULL,
    vl_preco_icms    NUMBER(10,2) NOT NULL,
    vl_perc_ipi      NUMBER(5,2) NOT NULL,
    vl_perc_icms     NUMBER(5,2) NOT NULL,
    sk_produto       NUMBER NOT NULL,
    sk_cliente       NUMBER NOT NULL,
    sk_vendedor      NUMBER NOT NULL,
    sk_operador      NUMBER NOT NULL,
    sk_tempo         NUMBER NOT NULL
);

ALTER TABLE fto_venda ADD CONSTRAINT fto_venda_pk PRIMARY KEY ( sk_venda );

ALTER TABLE fto_venda
    ADD CONSTRAINT fto_v_cli_fk FOREIGN KEY ( sk_cliente )
        REFERENCES dim_cliente ( sk_cliente );

ALTER TABLE fto_venda
    ADD CONSTRAINT fto_v_oper_fk FOREIGN KEY ( sk_operador )
        REFERENCES dim_operacao ( sk_operador );

ALTER TABLE fto_venda
    ADD CONSTRAINT fto_v_prod_fk FOREIGN KEY ( sk_produto )
        REFERENCES dim_produto ( sk_produto );

ALTER TABLE fto_venda
    ADD CONSTRAINT fto_v_temp_fk FOREIGN KEY ( sk_tempo )
        REFERENCES dim_tempo ( sk_tempo );

ALTER TABLE fto_venda
    ADD CONSTRAINT fto_v_vend_fk FOREIGN KEY ( sk_vendedor )
        REFERENCES dim_vendedor ( sk_vendedor );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
